name: FTP Upload

on:
  push:
    branches:
      - main

jobs:

  pre-deploy:
    name: 🎉 Pre-Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Connect SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd public_html/
            php artisan down

  web-deploy:

    name: 🎉 Deploy to Production
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server-dir: public_html/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/docker*/**


  post-deploy:
    name: 🎉 Post-Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: web-deploy
    steps:
      - name: Connect SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd public_html/
            php artisan up
            # php artisan env:set BUILD_ID ${{ github.run_number }} # To use this, check out my package. Run 'composer require levizoesch/laravelsetenvironment' then you can run the artisan command 'php artisan env:set BUILD_ID 1.15.86'
